name = "wechat-world-push"
main = "src/index.ts"
compatibility_date = "2025-05-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[triggers]
crons = [
  "0 0 * * *",   # 08:00 CST
  "0 2 * * *",   # 10:00 CST
  "0 4 * * *",   # 12:00 CST
  "0 6 * * *",   # 14:00 CST
  "0 8 * * *",   # 16:00 CST
  "0 10 * * *",  # 18:00 CST
  "0 12 * * *",  # 20:00 CST
  "0 14 * * *",  # 22:00 CST
]

[[routes]]
pattern = "wwc.ha7ch.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "wechat-world-push"
database_id = "c9750205-e088-4c9a-a30e-44d47da3fbfd"
